name: Daily

on:
  schedule:
    - cron: 0 0 * * *

jobs:
  stations:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.2
      - run: yarn install --immutable
      - run: node ./scripts/get-stations.js > ./data/stations.json
      - uses: peter-evans/create-pull-request@v3
        with:
          commit-message: Update stations.json
          branch: update-stations
          title: Update stations.json
